### ISSUE TITLE
Wrong logic for checking event key-code

### ISSUE THREAD

**Issue by AmirHosein-Gharaati** [jsbroks/vue-hangman#2]
https://github.com/jsbroks/vue-hangman/blob/f1459c7303b22aee5e68b2652d295a87c3348857/src/App.vue#L62

This is a wrong logic !
If the key was alphabetical, then it should be pushed into guessedLetters. Otherwise, we don't check that.
So the logic would be :
```javascript 
if (event.keyCode < 65 || event.keyCode > 90) return
```

**Comment by jsbroks** [comment]
PRs are welcome!
